language: php

php:
  - 7.1
  - 7.1snapshot
  - 7.2
  - 7.2snapshot

branches:
  only:
    - master
    - development
    - /^feature\/.+$/
    - /^refactoring\/.+$/
    - /^issue\/.+$/

before_script:
 - echo $(phpenv version-name)
 - sudo mkdir -pm 0777 /var/run
 - sudo usermod -a -G travis www-data
 - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
 - sudo cp env/php-fpm/$(phpenv version-name)/network-socket.pool.conf ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/network-socket.pool.conf
 - sudo cp env/php-fpm/$(phpenv version-name)/unix-domain-socket.pool.conf ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/unix-domain-socket.pool.conf
 - sudo cp env/php-fpm/$(phpenv version-name)/restricted-unix-domain-socket.pool.conf ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/restricted-unix-domain-socket.pool.conf
 - sudo ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
 - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git checkout "$TRAVIS_BRANCH"; else git checkout -b "$TRAVIS_PULL_REQUEST_BRANCH"; fi
 - git reset --hard "$TRAVIS_COMMIT"
 - composer self-update
 - mkdir -p vendor/bin
 - mkdir -p build/logs
 - composer install -o --prefer-dist --no-interaction

script:
 - php vendor/bin/phpunit.phar -c build/

after_success:
 - travis_retry php vendor/bin/coveralls.phar -v --exclude-no-stmt
