language: php

php:
  - 7.1
  - 7.1snapshot

branches:
  only:
    - master
    - development
    - /^feature\/.+$/
    - /^refactoring\/.+$/
    - /^issue\/.+$/

before_script:
 - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
 - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf
 - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
 - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git checkout "$TRAVIS_BRANCH"; else git checkout -b "$TRAVIS_PULL_REQUEST_BRANCH"; fi
 - git reset --hard "$TRAVIS_COMMIT"
 - composer self-update
 - mkdir -p vendor/bin
 - composer install -o --prefer-dist --no-interaction
 - mkdir build/logs

script:
 - php vendor/bin/phpunit.phar -c build/

after_success:
 - travis_retry php vendor/bin/coveralls.phar -v --exclude-no-stmt
